### ISSUE TITLE
Broken HTML syntax

### ISSUE THREAD

**Issue by ADobrodey** [deepan4cloud/terraform-aws-simple-httpserver#1]
https://github.com/deepan4cloud/terraform-aws-simple-httpserver/blob/b38bf525347b8a13abede3f5e49f74f4754677cd/index.html#L11

There is mismatch of html tags, nothing dangerous

**Comment by deepanrepo** [comment]
Thanks for highlighting this issue @ADobrodey. I've fixed it now :)
