### ISSUE TITLE
String instead of number

### ISSUE THREAD

**Issue by ADobrodey** [deepan4cloud/terraform-aws-simple-httpserver#3]
https://github.com/deepan4cloud/terraform-aws-simple-httpserver/blob/b38bf525347b8a13abede3f5e49f74f4754677cd/variables.tf#L18

Here is better to use number and overall I like that first 3 variables you declared with types, but then didn't used types/descriptions

**Comment by deepanrepo** [comment]
Thanks for the suggestion @ADobrodey. I have updated the variables as you would like :)
